apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators: 
          - git:
              repoURL: 'https://github.com/danielmarom78/discount-appset.git'
              revision: HEAD
              files:
                - path: 'dev/apps/*.yaml'
              values:
                appFile: '{{ path.filename }}'
                appName: '{{ path.filenameNormalized }}'
          - git:
              repoURL: 'https://github.com/danielmarom78/discount-appset.git'
              revision: HEAD
              files:
                - path: 'dev/envConfig.yaml'
  strategy:
  type: RollingSync
  rollingSync:
    steps:
      maxUpdate: 10%        
  template:  
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        targetRevision: HEAD
        path: 'dev/_chart'
        helm:
          valueFiles: 
            - '{{envValueFiles}}'
            - '{{appValuesFiles}}'
            - '../apps/{{appFile}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'dev'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true


