apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        revision: HEAD
        files:
          - path: dev/**/config.yaml
  template:
    spec:
      project: default
      source:
        repoURL: https://github.com/danielmarom78/discount-appset.git'
        targetRevision: HEAD
        path: '{{path.basename}}'
        helm:
          valueFiles:
            - 'dev/values.yaml'
            - '{{.valueFiles.1}}'
            - '{{.valueFiles.2}}'
            - '{{.valueFiles.3}}'
            - '{{.valueFiles.4}}'
            - '{{.valueFiles.5}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'dev'