apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  generators:
    - git:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        revision: HEAD
        files:
          - path: dev/apps/*.yaml
  strategy:
  type: RollingSync
  rollingSync:
    steps:
      maxUpdate: 10%        
  template:

  
    metadata:
      name: '{{ .path.filename | trimSuffix ".yaml" }}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        targetRevision: HEAD
        path: 'dev/_chart'
        helm:
          valueFiles: 
            - '../config/global-defaults-1.yaml'
            - '../config/global-defaults-2.yaml'
            - '{{.appValuesFiles}}'
            - '{{ (printf "../apps/%s" .path.filename) }}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'dev'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true


