apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: openshift-gitops
spec:
  generators:

    - matrix:
        generators:
          - git:
              repoURL: 'https://github.com/danielmarom78/discount-appset.git'
              revision: HEAD
              files:
                - path: 'dev/apps/*.yaml'
              pathParamPrefix: app  
              values:
                appFile: '{{app.path.filename}}'
                applName: '{{app.path.filenameNormalized}}'
          - git:
              repoURL: 'https://github.com/danielmarom78/discount-appset.git'
              revision: HEAD
              files:
                - path: 'dev/envConfig.yaml'
              pathParamPrefix: env
  strategy:
    type: RollingSync
  rollingSync:
    steps:
      maxUpdate: 10%        
  template:  
    metadata:
      name: '{{values.applName}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        targetRevision: HEAD
        path: 'dev/_chart'
        helm:
          valuesObject:                        
              uniqueValue: TRIGGER-BY-CHANGING    
          valueFiles: 
            - '{{envValueFiles}}'
            - '{{appValuesFiles}}'
            - '../apps/{{values.appFile}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'discount'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true