apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        revision: HEAD
        files:
          - path: dev/apps/*.yaml
  strategy:
  type: RollingSync
  rollingSync:
    steps:
      maxUpdate: 10%        
  template:  
    metadata:
      name: '{{ path.filename }}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        targetRevision: HEAD
        path: 'dev/_chart'
        helm:
          valueFiles: 
            - '{{ envValueFiles }}'
            - '{{ appValuesFiles }}'
            - '../apps/{{path.filename}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'dev'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true


