{{- $bucketCpuCounts := list 0 0 0 0 0 0 0 0 0 0 -}}
{{- $SurgeCpu := 5 -}}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - git: #App
              repoURL: 'https://github.com/danielmarom78/discount-appset.git'
              revision: HEAD
              files:
                - path: 'dyn/apps/*.yaml'
              pathParamPrefix: app  
              values:
                appFile: '{{app.path.filename}}'
                applName: '{{app.path.filenameNormalized}}'
                jobCPU: '{{job.resources.limits.cpu}}'
                deploymentCPU: '{{deployment.resources.limits.cpu}}'
          - git: #Env
              repoURL: 'https://github.com/danielmarom78/discount-appset.git'
              revision: HEAD
              files:
                - path: 'dyn/envConfig.yaml'
              pathParamPrefix: env
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 1
          maxUpdate: 100%
          steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 2
          maxUpdate: 100%
          steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 3
          maxUpdate: 100%
          steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 4
          maxUpdate: 100%
          steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 5
          maxUpdate: 100%
          steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 6
          maxUpdate: 100%
          steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 7
          maxUpdate: 100%
          steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 8
          maxUpdate: 100%
          steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 9
          maxUpdate: 100%
          steps:
        - matchExpressions:
            - key: SyncWave
              operator: In
              values:
                - 10
          maxUpdate: 100%

  template:  
    metadata:
      name: '{{values.applName}}'
      labels:
        envLabel: env-dev
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        targetRevision: HEAD
        path: 'dev/_chart'
        helm:
          # valuesObject:
          #   some-example-chart:                     
          #     uniqueValue: TRIGGER-BY-CHANGING
          valueFiles: 
            - '{{envValueFiles}}'
            - '{{appValuesFiles}}'
            - '../apps/{{values.appFile}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'discount'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true