apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace }}
spec:
  selector:
    labels:
      matchLabels:
        quota/id: {{ .Values.namespace }}
  quota:
    hard: {{ .Values.quota | toYaml | nindent 6 }}