{{- $uniqueValue := sha256sum .Values.uniqueValue  -}}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ printf "%s-job" .Release.Name | trunc 63 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  activeDeadlineSeconds: {{ .Values.job.timeout }}
  backoffLimit: {{ .Values.job.retries }}
  template:
    metadata:
      name: job
      labels:
        app: job
    spec:
      restartPolicy: Never
      containers:
      - name: job
        image: {{ .Values.imageName }}
        imagePullPolicy: IfNotPresent

        {{- with .Values.job.commandArgs }}
        args: {{ toJson . }}
        {{- end }}
        {{- with .Values.job.command }}
        command: {{ toJson . }}
        {{- end }}

        env:
        - name: {{ .Values.jobOutputFileEnvVar }}
          value: {{ printf "/mnt/job-outputs/%s-%s" .Release.Name $uniqueValue}}

        volumeMounts:
         - name: job-outputs
           mountPath: /mnt/job-outputs

      volumes:
        - name: job-outputs
          persistentVolumeClaim:
            claimName: common-pvc