apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: openshift-gitops
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  generators:
    - matrix:
        generators:
          - git: #App
              repoURL: 'https://github.com/danielmarom78/discount-appset.git'
              revision: HEAD
              files:
                - path: 'uat/apps/*.yaml'
              pathParamPrefix: app  
              values:
                appFile: '{{app.path.filename}}'
                applName: '{{app.path.filenameNormalized}}'
          - git: #Env
              repoURL: 'https://github.com/danielmarom78/discount-appset.git'
              revision: HEAD
              files:
                - path: 'uat/envConfig.yaml'
              pathParamPrefix: env
  # strategy:
  #   type: RollingSync
  #   rollingSync:
  #     steps:
  #       - matchExpressions:
  #           - key: envLabel
  #             operator: NotIn
  #             values:
  #               - xxx
  #         maxUpdate: 1%      
  template:  
    metadata:
      name: '{{values.applName}}'
      labels:
        envLabel: 'env-uat'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielmarom78/discount-appset.git'
        targetRevision: HEAD
        path: 'uat/_chart'
        helm:
          valuesObject:
            some-example-chart:                     
              uniqueValue: TRIGGER-BY-CHANGING-NEW1111
          valueFiles: 
            - '{{envValueFiles}}'
            - '{{appValuesFiles}}'
            - '../apps/{{values.appFile}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'discount'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true