{{- $uniqueValue := sha256sum .Values.uniqueValue  -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels: 
    argocd.argoproj.io/hook: PreSync
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    checksum/config: {{ $uniqueValue | trunc 44}}
data:
  values: {{ .Values | toJson | squote }}

